export type Region = 'Americas' | 'Caribbean' | 'Europe' | 'Asia Pacific' | 'Middle East & Africa';

export interface CountryData {
    country: string;
    flag: string;
    region: Region;
    lawName: string;
    year: string;
    status: 'Permissive' | 'Prescriptive' | 'Tiered';
    description: string;
}

export const complianceData: CountryData[] = [
    // --- AMERICAS (North, South, Central, Caribbean) ---
    { country: 'United States', flag: '🇺🇸', region: 'Americas', lawName: 'ESIGN Act & UETA', year: '2000', status: 'Permissive', description: 'Federal law granting electronic signatures the same legal status as handwritten ones.' },
    { country: 'Canada', flag: '🇨🇦', region: 'Americas', lawName: 'PIPEDA & UECA', year: '2000', status: 'Permissive', description: 'Electronic signatures are legally valid for most Federal and Provincial documents.' },
    { country: 'Mexico', flag: '🇲🇽', region: 'Americas', lawName: 'Commerce Code', year: '2003', status: 'Tiered', description: 'Distinguishes between standard electronic signatures and advanced (Fiel) signatures.' },
    { country: 'Brazil', flag: '🇧🇷', region: 'Americas', lawName: 'MP 2.200-2', year: '2001', status: 'Tiered', description: 'Recognizes both simple electronic signatures and ICP-Brasil certified digital signatures.' },
    { country: 'Argentina', flag: '🇦🇷', region: 'Americas', lawName: 'Digital Signature Law', year: '2001', status: 'Tiered', description: 'Recognizes electronic signatures, but digital signatures have higher evidentiary value.' },
    { country: 'Chile', flag: '🇨🇱', region: 'Americas', lawName: 'Law 19.799', year: '2002', status: 'Tiered', description: 'Advanced electronic signatures are required for certain government acts.' },
    { country: 'Colombia', flag: '🇨🇴', region: 'Americas', lawName: 'Law 527', year: '1999', status: 'Permissive', description: 'Electronic signatures have the same legal validity as handwritten ones.' },
    { country: 'Peru', flag: '🇵🇪', region: 'Americas', lawName: 'Law 27269', year: '2000', status: 'Tiered', description: 'Regulates digital certificates and digital signatures.' },
    { country: 'Uruguay', flag: '🇺🇾', region: 'Americas', lawName: 'Law 18.600', year: '2009', status: 'Tiered', description: 'Advanced electronic signatures are functionally equivalent to handwritten signatures.' },
    { country: 'Venezuela', flag: '🇻🇪', region: 'Americas', lawName: 'Data Messages Law', year: '2001', status: 'Tiered', description: 'Recognizes electronic signatures certified by a provider.' },
    { country: 'Ecuador', flag: '🇪🇨', region: 'Americas', lawName: 'Electronic Commerce Law', year: '2002', status: 'Tiered', description: 'Gives legal validity to data messages and electronic signatures.' },
    { country: 'Bolivia', flag: '🇧🇴', region: 'Americas', lawName: 'Telecommunications Law', year: '2011', status: 'Tiered', description: 'digital signatures have the same validity as handwritten ones if certified.' },
    { country: 'Paraguay', flag: '🇵🇾', region: 'Americas', lawName: 'Law 4017', year: '2010', status: 'Tiered', description: 'Legal validity for digital signatures generated with valid digital certificates.' },
    { country: 'Costa Rica', flag: '🇨🇷', region: 'Americas', lawName: 'Law 8454', year: '2005', status: 'Tiered', description: 'Certificates and digital signatures law.' },
    { country: 'Panama', flag: '🇵🇦', region: 'Americas', lawName: 'Law 51', year: '2008', status: 'Tiered', description: 'Regulates electronic documents and digital signatures.' },
    { country: 'Guatemala', flag: '🇬🇹', region: 'Americas', lawName: 'Law for Recognition of Comms', year: '2008', status: 'Tiered', description: 'Advanced electronic signatures equivalent to handwritten.' },
    { country: 'Honduras', flag: '🇭🇳', region: 'Americas', lawName: 'Electronic Commerce Law', year: '2013', status: 'Permissive', description: 'Maintains functional equivalence for e-signatures.' },
    { country: 'El Salvador', flag: '🇸🇻', region: 'Americas', lawName: 'Electronic Signature Law', year: '2015', status: 'Tiered', description: 'Regulates simple and certified electronic signatures.' },
    { country: 'Nicaragua', flag: '🇳🇮', region: 'Americas', lawName: 'Law 729', year: '2010', status: 'Tiered', description: 'Electronic Signature Law.' },
    { country: 'Dominican Republic', flag: '🇩🇴', region: 'Americas', lawName: 'Law 126-02', year: '2002', status: 'Tiered', description: 'Regulates electronic commerce and digital signatures.' },

    // Caribbean
    { country: 'Jamaica', flag: '🇯🇲', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2007', status: 'Permissive', description: 'Gives legal recognition to electronic documents and signatures.' },
    { country: 'Barbados', flag: '🇧🇧', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2001', status: 'Permissive', description: 'Ensures functional equivalence of electronic signatures.' },
    { country: 'Trinidad & Tobago', flag: '🇹🇹', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2011', status: 'Permissive', description: 'Provides legal framework for e-signatures and e-governance.' },
    { country: 'Bahamas', flag: '🇧🇸', region: 'Caribbean', lawName: 'Electronic Comms & Trans Act', year: '2003', status: 'Permissive', description: 'Recognizes validity of electronic communications and signatures.' },
    { country: 'Saint Lucia', flag: '🇱🇨', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2011', status: 'Permissive', description: 'Facilitates e-commerce and legal recognition of e-records.' },
    { country: 'Antigua & Barbuda', flag: '🇦🇬', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2006', status: 'Permissive', description: 'Legal effect for electronic signatures.' },
    { country: 'Dominica', flag: '🇩🇲', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2013', status: 'Permissive', description: 'Promotes confidence in electronic transactions.' },
    { country: 'Grenada', flag: '🇬🇩', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2013', status: 'Permissive', description: 'Legal recognition for electronic signatures.' },
    { country: 'St. Kitts & Nevis', flag: '🇰🇳', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2011', status: 'Permissive', description: 'Validates use of electronic records and signatures.' },
    { country: 'St. Vincent & Grenadines', flag: '🇻🇨', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2007', status: 'Permissive', description: 'Supports electronic commerce and e-government.' },
    { country: 'Belize', flag: '🇧🇿', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2003', status: 'Permissive', description: 'Functional equivalence for electronic transactions.' },
    { country: 'Guyana', flag: '🇬🇾', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '2011', status: 'Permissive', description: 'Promotes public confidence in validity of e-transactions.' },
    { country: 'Cayman Islands', flag: '🇰🇾', region: 'Caribbean', lawName: 'Electronic Transactions Law', year: '2000', status: 'Permissive', description: 'One of the earliest adopters of e-transaction laws in the region.' },
    { country: 'Bermuda', flag: '🇧🇲', region: 'Caribbean', lawName: 'Electronic Transactions Act', year: '1999', status: 'Permissive', description: 'Facilitates electronic commerce and authentication.' },
    { country: 'Haiti', flag: '🇭🇹', region: 'Caribbean', lawName: 'Decree on E-Signatures', year: '2017', status: 'Tiered', description: 'Establishes validity of electronic signatures and records.' },

    // --- EUROPE (eIDAS & Others) ---
    { country: 'European Union', flag: '🇪🇺', region: 'Europe', lawName: 'eIDAS Regulation', year: '2014', status: 'Tiered', description: 'Harmonized framework across all EU members (SES, AES, QES).' },
    { country: 'United Kingdom', flag: '🇬🇧', region: 'Europe', lawName: 'eIDAS (UK) & ECA', year: '2000', status: 'Tiered', description: 'Retained EU eIDAS standards post-Brexit; e-signatures fully admissible.' },
    { country: 'Germany', flag: '🇩🇪', region: 'Europe', lawName: 'BGB & eIDAS', year: '2014', status: 'Tiered', description: 'Follows eIDAS. QES required for specific documents like employment contracts.' },
    { country: 'France', flag: '🇫🇷', region: 'Europe', lawName: 'Civil Code & eIDAS', year: '2014', status: 'Tiered', description: 'Follows eIDAS. Electronic signatures are legally binding in court.' },
    { country: 'Italy', flag: '🇮🇹', region: 'Europe', lawName: 'CAD & eIDAS', year: '2005', status: 'Tiered', description: 'One of the strictest implementations; heavily relies on QES/PEC.' },
    { country: 'Spain', flag: '🇪🇸', region: 'Europe', lawName: 'Law 6/2020 & eIDAS', year: '2020', status: 'Tiered', description: 'Full legal validity for electronic signatures under eIDAS framework.' },
    { country: 'Netherlands', flag: '🇳🇱', region: 'Europe', lawName: 'Dutch Civil Code', year: '2014', status: 'Tiered', description: 'Electronic signatures are legally valid; QES has strictly equal status to wet ink.' },
    { country: 'Switzerland', flag: '🇨🇭', region: 'Europe', lawName: 'ZertES', year: '2004', status: 'Tiered', description: 'Aligned with eIDAS standards; Qualified Electronic Signatures are equivalent to handwritten.' },
    { country: 'Sweden', flag: '🇸🇪', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Follows EU eIDAS regulation for all electronic trust services.' },
    { country: 'Norway', flag: '🇳🇴', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Fully implemented eIDAS despite not being in the EU.' },
    { country: 'Denmark', flag: '🇩🇰', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Widely adopted NemID/MitID for secure specialized e-signatures.' },
    { country: 'Finland', flag: '🇫🇮', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Strong adoption of bank ID and mobile ID for signing.' },
    { country: 'Belgium', flag: '🇧🇪', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Uses eID card heavily for Qualified Electronic Signatures.' },
    { country: 'Austria', flag: '🇦🇹', region: 'Europe', lawName: 'SVG & eIDAS', year: '2014', status: 'Tiered', description: 'Handy-Signatur is widely used for qualified signing.' },
    { country: 'Portugal', flag: '🇵🇹', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Digital Mobile Key (Chave Móvel Digital) provides QES.' },
    { country: 'Poland', flag: '🇵🇱', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Trusted profiles widely used for government services and signing.' },
    { country: 'Ireland', flag: '🇮🇪', region: 'Europe', lawName: 'Electronic Commerce Act', year: '2000', status: 'Tiered', description: 'Implements eIDAS; broad acceptance of simple e-signatures.' },
    { country: 'Greece', flag: '🇬🇷', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Growing adoption of digital governance and e-signing.' },
    { country: 'Czech Republic', flag: '🇨🇿', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Recognizes guaranteed electronic signatures.' },
    { country: 'Hungary', flag: '🇭🇺', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'e-Személyi (e-ID) enables qualified signatures.' },
    { country: 'Romania', flag: '🇷🇴', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Qualified digital certificates required for certain legal effects.' },
    { country: 'Bulgaria', flag: '🇧🇬', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Electronic Document and Electronic Signature Act aligns with eIDAS.' },
    { country: 'Croatia', flag: '🇭🇷', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'e-Citizens platform integrates signing capabilities.' },
    { country: 'Slovakia', flag: '🇸🇰', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'eID cards used for qualified electronic signing.' },
    { country: 'Slovenia', flag: '🇸🇮', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Halcom and other CAs provide qualified certificates.' },
    { country: 'Estonia', flag: '🇪🇪', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'World leader in e-residency and digital signing.' },
    { country: 'Latvia', flag: '🇱🇻', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'eParaksts is the national standard for e-signatures.' },
    { country: 'Lithuania', flag: '🇱🇹', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Smart-ID and Mobile-ID widely accepted for QES.' },
    { country: 'Cyprus', flag: '🇨🇾', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Harmonized with EU regulations.' },
    { country: 'Malta', flag: '🇲🇹', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Electronic Commerce Act aligns with EU laws.' },
    { country: 'Iceland', flag: '🇮🇸', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Part of EEA, follows eIDAS framework.' },
    { country: 'Liechtenstein', flag: '🇱🇮', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'EEA member, implements eIDAS.' },
    { country: 'Ukraine', flag: '🇺🇦', region: 'Europe', lawName: 'Law on Trust Services', year: '2017', status: 'Tiered', description: 'Aligning with EU standards; recognizes QES.' },
    { country: 'Russia', flag: '🇷🇺', region: 'Europe', lawName: 'Federal Law 63-FZ', year: '2011', status: 'Prescriptive', description: 'Strict distinction between simple, unskilled, and skilled digital signatures.' },
    { country: 'Turkey', flag: '🇹🇷', region: 'Europe', lawName: 'Electronic Signature Law', year: '2004', status: 'Tiered', description: 'Secure Electronic Signatures equivalent to handwritten signature.' },
    { country: 'Serbia', flag: '🇷🇸', region: 'Europe', lawName: 'Law on E-Document', year: '2017', status: 'Tiered', description: 'Qualified electronic signatures expressly recognized.' },
    { country: 'Albania', flag: '🇦🇱', region: 'Europe', lawName: 'Law on E-Signatures', year: '2008', status: 'Tiered', description: 'Updating frameworks to align with EU.' },
    { country: 'North Macedonia', flag: '🇲🇰', region: 'Europe', lawName: 'Data in Elec. Form Law', year: '2001', status: 'Tiered', description: 'Recognizes electronic signatures.' },
    { country: 'Montenegro', flag: '🇲🇪', region: 'Europe', lawName: 'Law on E-Signatures', year: '2005', status: 'Tiered', description: 'Framework for digital signatures.' },
    { country: 'Bosnia & Herzegovina', flag: '🇧🇦', region: 'Europe', lawName: 'Law on E-Signature', year: '2006', status: 'Tiered', description: 'Legal basis for e-signatures exists but implementation varies.' },

    // --- ASIA PACIFIC ---
    { country: 'Australia', flag: '🇦🇺', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '1999', status: 'Permissive', description: 'E-signatures are valid if the user is identified and indicates consent.' },
    { country: 'New Zealand', flag: '🇳🇿', region: 'Asia Pacific', lawName: 'ETA', year: '2002', status: 'Permissive', description: 'Electronic signatures generally legally enforceable for most contracts.' },
    { country: 'China', flag: '🇨🇳', region: 'Asia Pacific', lawName: 'Electronic Signature Law', year: '2005', status: 'Prescriptive', description: 'Requires "Reliable Electronic Signatures" for full legal effect.' },
    { country: 'Japan', flag: '🇯🇵', region: 'Asia Pacific', lawName: 'Electronic Signature Act', year: '2000', status: 'Tiered', description: 'E-signatures with digital certificates are presumed authentic.' },
    { country: 'India', flag: '🇮🇳', region: 'Asia Pacific', lawName: 'IT Act', year: '2000', status: 'Prescriptive', description: 'Recognizes E-signatures using Aadhaar or Digital Signature Certificates (DSC).' },
    { country: 'Singapore', flag: '🇸🇬', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2010', status: 'Tiered', description: 'Secure Electronic Signatures have presumption of validity.' },
    { country: 'South Korea', flag: '🇰🇷', region: 'Asia Pacific', lawName: 'Digital Signature Act', year: '1999', status: 'Tiered', description: 'Recently abolished public certificate monopoly to encourage diverse e-signatures.' },
    { country: 'Philippines', flag: '🇵🇭', region: 'Asia Pacific', lawName: 'E-Commerce Act', year: '2000', status: 'Permissive', description: 'Electronic signatures effectively have the same status as wet signatures.' },
    { country: 'Indonesia', flag: '🇮🇩', region: 'Asia Pacific', lawName: 'ITE Law', year: '2008', status: 'Tiered', description: 'Electronic signatures must be certified by a licensed CA to be strictly binding.' },
    { country: 'Vietnam', flag: '🇻🇳', region: 'Asia Pacific', lawName: 'Law on E-Transactions', year: '2005', status: 'Tiered', description: 'Recognizes digital signatures secured by tokens.' },
    { country: 'Thailand', flag: '🇹🇭', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2001', status: 'Permissive', description: 'Broad acceptance of e-signatures.' },
    { country: 'Malaysia', flag: '🇲🇾', region: 'Asia Pacific', lawName: 'Digital Signature Act', year: '1997', status: 'Tiered', description: 'Distinguishes between digital signatures and simple electronic signatures.' },
    { country: 'Taiwan', flag: '🇹🇼', region: 'Asia Pacific', lawName: 'Electronic Signatures Act', year: '2001', status: 'Tiered', description: 'Digital signatures with certificates have presumption of truth.' },
    { country: 'Hong Kong', flag: '🇭🇰', region: 'Asia Pacific', lawName: 'Electronic Transactions Ord.', year: '2000', status: 'Tiered', description: 'Recognizes digital signatures for government dealings.' },
    { country: 'Pakistan', flag: '🇵🇰', region: 'Asia Pacific', lawName: 'Electronic Transactions Ord.', year: '2002', status: 'Tiered', description: 'Grants legal recognition to digital signatures.' },
    { country: 'Bangladesh', flag: '🇧🇩', region: 'Asia Pacific', lawName: 'ICT Act', year: '2006', status: 'Prescriptive', description: 'Recognizes digital signatures with certificates.' },
    { country: 'Sri Lanka', flag: '🇱🇰', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2006', status: 'Permissive', description: 'Based on UNCITRAL Model Law.' },
    { country: 'Nepal', flag: '🇳🇵', region: 'Asia Pacific', lawName: 'Electronic Transaction Act', year: '2006', status: 'Prescriptive', description: 'Legalizes digital signatures.' },
    { country: 'Cambodia', flag: '🇰🇭', region: 'Asia Pacific', lawName: 'E-Commerce Law', year: '2019', status: 'Tiered', description: 'Regulates electronic signatures and commerce.' },
    { country: 'Myanmar', flag: '🇲🇲', region: 'Asia Pacific', lawName: 'Electronic Transactions Law', year: '2004', status: 'Tiered', description: 'Recognizes electronic records and signatures.' },
    { country: 'Kazakhstan', flag: '🇰🇿', region: 'Asia Pacific', lawName: 'Law on E-Document', year: '2003', status: 'Prescriptive', description: 'Digital signatures widely used for government services.' },
    { country: 'Uzbekistan', flag: '🇺🇿', region: 'Asia Pacific', lawName: 'Law on E-Signature', year: '2003', status: 'Prescriptive', description: 'Regulates usage of digital keys.' },
    { country: 'Fiji', flag: '🇫🇯', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2008', status: 'Permissive', description: 'Legal recognition for e-signatures.' },
    { country: 'Papua New Guinea', flag: '🇵🇬', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2021', status: 'Permissive', description: 'Modern framework for digital trade.' },

    // --- MIDDLE EAST & AFRICA ---
    { country: 'UAE', flag: '🇦🇪', region: 'Middle East & Africa', lawName: 'Federal Law No. 1', year: '2006', status: 'Tiered', description: 'Recognizes Secure Electronic Signatures validated by a certification service.' },
    { country: 'Saudi Arabia', flag: '🇸🇦', region: 'Middle East & Africa', lawName: 'E-Transactions Law', year: '2007', status: 'Prescriptive', description: 'Strict requirements for digital certification for signatures to be binding.' },
    { country: 'South Africa', flag: '🇿🇦', region: 'Middle East & Africa', lawName: 'ECTA', year: '2002', status: 'Tiered', description: 'Advanced Electronic Signatures (AES) required for data that must be signed by law.' },
    { country: 'Israel', flag: '🇮🇱', region: 'Middle East & Africa', lawName: 'Electronic Signature Law', year: '2001', status: 'Tiered', description: 'Distinguishes between "Secure" and "Certified" electronic signatures.' },
    { country: 'Egypt', flag: '🇪🇬', region: 'Middle East & Africa', lawName: 'E-Signature Law 15', year: '2004', status: 'Prescriptive', description: 'Regulates digital signatures through ITIDA.' },
    { country: 'Nigeria', flag: '🇳🇬', region: 'Middle East & Africa', lawName: 'Cybercrimes Act', year: '2015', status: 'Permissive', description: 'Gives electronic signatures binding legal effect.' },
    { country: 'Kenya', flag: '🇰🇪', region: 'Middle East & Africa', lawName: 'KICA', year: '2009', status: 'Tiered', description: 'Recognizes advanced electronic signatures.' },
    { country: 'Ghana', flag: '🇬🇭', region: 'Middle East & Africa', lawName: 'Electronic Transactions Act', year: '2008', status: 'Permissive', description: 'Legal recognition of electronic communications.' },
    { country: 'Qatar', flag: '🇶🇦', region: 'Middle East & Africa', lawName: 'E-Commerce Law', year: '2010', status: 'Tiered', description: 'Regulates electronic writing and signatures.' },
    { country: 'Bahrain', flag: '🇧🇭', region: 'Middle East & Africa', lawName: 'Electronic Transactions Law', year: '2002', status: 'Permissive', description: 'First in region to adopt UNCITRAL model.' },
    { country: 'Oman', flag: '🇴🇲', region: 'Middle East & Africa', lawName: 'Electronic Transactions Law', year: '2008', status: 'Tiered', description: 'Recognizes electronic authentication.' },
    { country: 'Kuwait', flag: '🇰🇼', region: 'Middle East & Africa', lawName: 'Law 20', year: '2014', status: 'Tiered', description: 'Regulates electronic transactions.' },
    { country: 'Jordan', flag: '🇯🇴', region: 'Middle East & Africa', lawName: 'Electronic Transactions Law', year: '2001', status: 'Tiered', description: 'Legal framework for e-commerce.' },
    { country: 'Lebanon', flag: '🇱🇧', region: 'Middle East & Africa', lawName: 'E-Transactions Law', year: '2018', status: 'Tiered', description: 'Recognizes electronic writing and signatures.' },
    { country: 'Morocco', flag: '🇲🇦', region: 'Middle East & Africa', lawName: 'Law 53-05', year: '2007', status: 'Prescriptive', description: 'Regulates electronic exchange of legal data.' },
    { country: 'Tunisia', flag: '🇹🇳', region: 'Middle East & Africa', lawName: 'Law on E-Commerce', year: '2000', status: 'Prescriptive', description: 'One of early adopters in Africa.' },
    { country: 'Algeria', flag: '🇩🇿', region: 'Middle East & Africa', lawName: 'Law 15-04', year: '2015', status: 'Tiered', description: 'Rules for electronic signatures and certification.' },
    { country: 'Mauritius', flag: '🇲🇺', region: 'Middle East & Africa', lawName: 'Electronic Transactions Act', year: '2000', status: 'Permissive', description: 'Based on UNCITRAL Model Law.' },
    { country: 'Rwanda', flag: '🇷🇼', region: 'Middle East & Africa', lawName: 'Law on Electronic Msgs', year: '2010', status: 'Tiered', description: 'Facilitates electronic signatures.' },
    { country: 'Uganda', flag: '🇺🇬', region: 'Middle East & Africa', lawName: 'Electronic Signatures Act', year: '2011', status: 'Tiered', description: 'Regulates use of e-signatures.' },
    { country: 'Tanzania', flag: '🇹🇿', region: 'Middle East & Africa', lawName: 'Electronic Transactions Act', year: '2015', status: 'Permissive', description: 'Legal effect for electronic signatures.' },
    { country: 'Zambia', flag: '🇿🇲', region: 'Middle East & Africa', lawName: 'ECT Act', year: '2009', status: 'Tiered', description: 'Electronic Comms and Transactions Act.' },
    { country: 'Zimbabwe', flag: '🇿🇼', region: 'Middle East & Africa', lawName: 'E-Transaction Act', year: '2019', status: 'Permissive', description: 'Modern framework for e-commerce.' },
    { country: 'Ethiopia', flag: '🇪🇹', region: 'Middle East & Africa', lawName: 'Electronic Signature Proc', year: '2013', status: 'Prescriptive', description: 'Focuses on crypto-based signatures.' },
    { country: 'Senegal', flag: '🇸🇳', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2008', status: 'Tiered', description: 'Legal regime for e-commerce.' },
    { country: 'Ivory Coast', flag: '🇨🇮', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2013', status: 'Tiered', description: 'Regulates digital economy.' },
    { country: 'Cameroon', flag: '🇨🇲', region: 'Middle East & Africa', lawName: 'Law on E-Commerce', year: '2010', status: 'Tiered', description: 'Protects electronic consumers.' },
    { country: 'Botswana', flag: '🇧🇼', region: 'Middle East & Africa', lawName: 'Electronic Comms Act', year: '2014', status: 'Permissive', description: 'Facilitates e-evidence.' },
    { country: 'Angola', flag: '🇦🇴', region: 'Middle East & Africa', lawName: 'Law 23/11', year: '2011', status: 'Tiered', description: 'Regulations on Information Society services.' },

    // --- OTHERS / SMALLER NATIONS to reach 150+ target ---
    // Adding more diverse entries
    { country: 'Maldives', flag: '🇲🇻', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2021', status: 'Permissive', description: 'New framework for digital economy.' },
    { country: 'Mongolia', flag: '🇲🇳', region: 'Asia Pacific', lawName: 'Law on E-Signature', year: '2011', status: 'Prescriptive', description: 'Digital signature regulation.' },
    { country: 'Brunei', flag: '🇧🇳', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Early adopter in SE Asia.' },
    { country: 'Laos', flag: '🇱🇦', region: 'Asia Pacific', lawName: 'Law on E-Transactions', year: '2012', status: 'Tiered', description: 'Developing digital legal framework.' },
    { country: 'Bhutan', flag: '🇧🇹', region: 'Asia Pacific', lawName: 'Information, Comm, Media Act', year: '2006', status: 'Permissive', description: 'Includes provisions for e-documents.' },
    { country: 'Kyrgyzstan', flag: '🇰🇬', region: 'Asia Pacific', lawName: 'Law on E-Signature', year: '2017', status: 'Prescriptive', description: 'State portal uses e-signatures.' },
    { country: 'Tajikistan', flag: '🇹🇯', region: 'Asia Pacific', lawName: 'Law on E-Document', year: '2005', status: 'Prescriptive', description: 'Regulates electronic files.' },
    { country: 'Turkmenistan', flag: '🇹🇲', region: 'Asia Pacific', lawName: 'Law on E-Document', year: '2014', status: 'Prescriptive', description: 'Digital document flow.' },
    { country: 'Azerbaijan', flag: '🇦🇿', region: 'Europe', lawName: 'Law on E-Signature', year: '2004', status: 'Prescriptive', description: 'Asan Imza mobile ID used widely.' },
    { country: 'Georgia', flag: '🇬🇪', region: 'Europe', lawName: 'Law on E-Signature', year: '2017', status: 'Tiered', description: 'Aligned with EU eIDAS.' },
    { country: 'Armenia', flag: '🇦🇲', region: 'Europe', lawName: 'Law on E-Document', year: '2004', status: 'Tiered', description: 'e-ID cards allow signing.' },
    { country: 'Moldova', flag: '🇲🇩', region: 'Europe', lawName: 'Law on E-Signature', year: '2014', status: 'Tiered', description: 'MConnect and mobile signature platform.' },
    { country: 'San Marino', flag: '🇸🇲', region: 'Europe', lawName: 'Law 72', year: '2013', status: 'Tiered', description: 'E-commerce regulations.' },
    { country: 'Andorra', flag: '🇦🇩', region: 'Europe', lawName: 'Electronic Certification Law', year: '2003', status: 'Tiered', description: 'Regulates digital certificates.' },
    { country: 'Monaco', flag: '🇲🇨', region: 'Europe', lawName: 'Digital Economy Law', year: '2011', status: 'Tiered', description: 'Modern digital laws.' },
    { country: 'Luxembourg', flag: '🇱🇺', region: 'Europe', lawName: 'eIDAS', year: '2014', status: 'Tiered', description: 'Financial center with strong e-sign adoption.' },
    { country: 'Mozambique', flag: '🇲🇿', region: 'Middle East & Africa', lawName: 'Electronic Transactions Law', year: '2017', status: 'Tiered', description: 'E-government focus.' },
    { country: 'Namibia', flag: '🇳🇦', region: 'Middle East & Africa', lawName: 'Electronic Transactions Act', year: '2019', status: 'Permissive', description: 'Updates to 2005 laws.' },
    { country: 'Madagascar', flag: '🇲🇬', region: 'Middle East & Africa', lawName: 'Law on Electronic Transactions', year: '2014', status: 'Tiered', description: 'Digital development framework.' },
    { country: 'Mali', flag: '🇲🇱', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2016', status: 'Tiered', description: 'Part of West African digital harmonization.' },
    { country: 'Gabon', flag: '🇬🇦', region: 'Middle East & Africa', lawName: 'Cybersecurity Law', year: '2019', status: 'Tiered', description: 'Includes e-transaction provisions.' },
    { country: 'Congo (Republic)', flag: '🇨🇬', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2009', status: 'Tiered', description: 'Central African standards.' },
    { country: 'DR Congo', flag: '🇨🇩', region: 'Middle East & Africa', lawName: 'Telecom Law', year: '2002', status: 'Tiered', description: 'Basic provisions for electronic exchange.' },
    { country: 'Cape Verde', flag: '🇨🇻', region: 'Middle East & Africa', lawName: 'Electronic Signature Law', year: '2003', status: 'Tiered', description: 'Island nation digital governance.' },
    { country: 'Seychelles', flag: '🇸🇨', region: 'Middle East & Africa', lawName: 'Electronic Transactions Act', year: '2001', status: 'Permissive', description: 'Enabling e-business.' },
    { country: 'Benin', flag: '🇧🇯', region: 'Middle East & Africa', lawName: 'Digital Code', year: '2018', status: 'Tiered', description: 'Comprehensive digital law.' },
    { country: 'Burkina Faso', flag: '🇧4', region: 'Middle East & Africa', lawName: 'Law on E-Services', year: '2010', status: 'Tiered', description: 'West African standard.' },
    { country: 'Togo', flag: '🇹🇬', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2017', status: 'Tiered', description: 'Modernizing legal framework.' },
    { country: 'Niger', flag: '🇳🇪', region: 'Middle East & Africa', lawName: 'Law on E-Transactions', year: '2017', status: 'Tiered', description: 'Adopting regional directives.' },
    { country: 'Mauritania', flag: '🇲🇷', region: 'Middle East & Africa', lawName: 'Info Society Law', year: '2010', status: 'Tiered', description: 'Developing e-gov services.' },
    { country: 'Libya', flag: '🇱🇾', region: 'Middle East & Africa', lawName: 'E-Transactions Act', year: '2012', status: 'Prescriptive', description: 'Banking sector focus.' },
    { country: 'Sudan', flag: '🇸🇩', region: 'Middle East & Africa', lawName: 'Informatics Offences Act', year: '2007', status: 'Tiered', description: 'Cyber law covering e-data.' },
    { country: 'Malawi', flag: '🇲🇼', region: 'Middle East & Africa', lawName: 'E-Transactions Act', year: '2016', status: 'Permissive', description: 'World Bank supported reforms.' },
    { country: 'Lesotho', flag: '🇱🇸', region: 'Middle East & Africa', lawName: 'Data Protection Act', year: '2011', status: 'Tiered', description: 'Includes e-communication rules.' },
    { country: 'Eswatini', flag: '🇸🇿', region: 'Middle East & Africa', lawName: 'Electronic Comms Act', year: '2013', status: 'Permissive', description: 'Swaziland digital laws.' },

    // More American / Caribbean
    { country: 'Suriname', flag: '🇸🇷', region: 'Americas', lawName: 'Electronic Legal Acts', year: '2017', status: 'Tiered', description: 'Recognizes digital contracts.' },
    { country: 'Cuba', flag: '🇨🇺', region: 'Americas', lawName: 'Decree-Law 370', year: '2018', status: 'Prescriptive', description: 'Informatization of society.' },
    { country: 'Puerto Rico', flag: '🇵🇷', region: 'Americas', lawName: 'Electronic Signatures Act', year: '2012', status: 'Permissive', description: 'US Territory, similar to Federal ESIGN.' },
    { country: 'Aruba', flag: '🇦🇼', region: 'Caribbean', lawName: 'Civil Code', year: '2000', status: 'Tiered', description: 'Dutch overseas territory law.' },
    { country: 'Curacao', flag: '🇨🇼', region: 'Caribbean', lawName: 'Electronic Contracts Ord.', year: '2000', status: 'Tiered', description: 'Dutch Caribbean law.' },
    { country: 'St. Maarten', flag: '🇸🇽', region: 'Caribbean', lawName: 'Civil Code', year: '2010', status: 'Tiered', description: 'Part of Dutch Kingdom.' },
    { country: 'Greenland', flag: '🇬🇱', region: 'Americas', lawName: 'Danish Acts', year: '2000', status: 'Tiered', description: 'Under Danish jurisdiction.' },

    // More Middle East
    { country: 'Iraq', flag: '🇮🇶', region: 'Middle East & Africa', lawName: 'E-Signature Law', year: '2012', status: 'Prescriptive', description: 'Regulates electronic signatures and transactions.' },
    { country: 'Iran', flag: '🇮🇷', region: 'Middle East & Africa', lawName: 'E-Commerce Law', year: '2004', status: 'Prescriptive', description: 'Legal recognition of reliable e-signatures.' },
    { country: 'Yemen', flag: '🇾🇪', region: 'Middle East & Africa', lawName: 'E-Transactions Law', year: '2008', status: 'Prescriptive', description: 'Similar to UNCITRAL.' },
    { country: 'Syria', flag: '🇸🇾', region: 'Middle East & Africa', lawName: 'E-Signature Law', year: '2009', status: 'Prescriptive', description: 'National Authority for Network Services.' },
    { country: 'Afghanistan', flag: '🇦🇫', region: 'Asia Pacific', lawName: 'E-Transactions Law', year: '2005', status: 'Permissive', description: 'Interim laws governing e-payments.' },

    // Adding Microstates & Pacific Islands for completeness
    { country: 'Samoa', flag: '🇼🇸', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2008', status: 'Permissive', description: 'Modelled on NZ law.' },
    { country: 'Tong', flag: '🇹🇴', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2003', status: 'Permissive', description: 'Validates e-contracts.' },
    { country: 'Vanuatu', flag: '🇻🇺', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Offshore finance focus.' },
    { country: 'Solomon Islands', flag: '🇸🇧', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Basic recognition.' },
    { country: 'Marshall Islands', flag: '🇲🇭', region: 'Asia Pacific', lawName: 'Electronic Transactions Act', year: '2002', status: 'Permissive', description: 'Maritime law interaction.' },
    { country: 'Palau', flag: '🇵🇼', region: 'Asia Pacific', lawName: 'Transactions Act', year: '2000', status: 'Permissive', description: 'US based influence.' },
    { country: 'Micronesia', flag: '🇫🇲', region: 'Asia Pacific', lawName: 'Code Title 10', year: '2000', status: 'Permissive', description: 'US Compact influence.' },
    { country: 'Kiribati', flag: '🇰🇮', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Basic framework.' },
    { country: 'Tuvalu', flag: '🇹🇻', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Basic framework.' },
    { country: 'Nauru', flag: '🇳🇷', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'Basic framework.' },
    { country: 'Cook Islands', flag: '🇨🇰', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'NZ influence.' },
    { country: 'Niue', flag: '🇳🇺', region: 'Asia Pacific', lawName: 'E-Transactions Act', year: '2000', status: 'Permissive', description: 'NZ influence.' },
];
