"use node";
import { action } from "./_generated/server";
import { v } from "convex/values";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { internal } from "./_generated/api";

export const generate = action({
  args: {
    requestId: v.id("signatureRequests"),
    documentName: v.string(),
    signerName: v.string(),
    signerEmail: v.string(),
    signedAt: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // 1. Create PDF
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // 2. Draw Content
    // Header
    page.drawText('CERTIFICATE OF COMPLETION', {
      x: 50, y: height - 60, size: 18, font: boldFont, color: rgb(0, 0, 0),
    });
    
    page.drawText(`Document: ${args.documentName}`, {
        x: 50, y: height - 85, size: 10, font: font, color: rgb(0.3, 0.3, 0.3),
    });

    // Verify Badge
    page.drawRectangle({
        x: width - 140, y: height - 80, width: 90, height: 30,
        color: rgb(0.9, 1, 0.9),
    });
    page.drawText('SIGNED', {
        x: width - 118, y: height - 70, size: 12, font: boldFont, color: rgb(0, 0.5, 0),
    });

    // Fields Helper
    let y = height - 150;
    const drawField = (label: string, value: string) => {
        page.drawText(label, { x: 50, y, size: 10, font: boldFont, color: rgb(0.4, 0.4, 0.4) });
        page.drawText(value, { x: 200, y, size: 10, font: font, color: rgb(0, 0, 0) });
        y -= 25;
    };

    // Metadata
    page.drawText('Transaction Details', { x: 50, y: y + 10, size: 14, font: boldFont });
    y -= 20;
    drawField('Request ID:', args.requestId);
    drawField('Date Signed (UTC):', args.signedAt);
    drawField('Document Status:', 'Completed');
    
    y -= 20;
    page.drawText('Signer Identity', { x: 50, y: y + 10, size: 14, font: boldFont });
    y -= 20;
    drawField('Name:', args.signerName);
    drawField('Email:', args.signerEmail);
    if (args.ipAddress) drawField('IP Address:', args.ipAddress);
    if (args.userAgent) drawField('User Agent:', args.userAgent);

    // Footer
    page.drawLine({
        start: { x: 50, y: 50 },
        end: { x: width - 50, y: 50 },
        thickness: 1,
        color: rgb(0.8, 0.8, 0.8),
    });
    page.drawText(`Generated by SkySign on ${new Date().toISOString()}`, {
        x: 50, y: 35, size: 8, font: font, color: rgb(0.6, 0.6, 0.6),
    });

    // 3. Save & Upload
    const pdfBytes = await pdfDoc.save();
     
    const blob = new Blob([pdfBytes as unknown as BlobPart], { type: 'application/pdf' });
    
    const uploadUrl = await ctx.storage.generateUploadUrl();
    const result = await fetch(uploadUrl, {
      method: "POST",
      headers: { "Content-Type": "application/pdf" },
      body: blob,
    });
    
    if (!result.ok) throw new Error(`Upload failed: ${result.statusText}`);
    const { storageId } = await result.json();

    // 4. Save to DB
    await ctx.runMutation(internal.signatureRequests.saveCertificate, {
        requestId: args.requestId,
        storageId,
    });

    return storageId;
  }
});
